- name: setup redis server
  hosts: redis
  become: yes
  tasks:
  - name: Disable redis 
    ansible.builtin.command: dnf module disable redis -y

  - name: Enable dnf service
    ansible.builtin.command: dnf module enable redis:7 -y

  - name: Install the latest version of redis
    ansible.builtin.dnf:
      name: redis
      state: present

  - name: Allow remote connections
    ansible.builtin.replace:
      path: /etc/redis/redis.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'

  - name: disable proctected mode
    ansible.builtin.lineinfile:
      path: /etc/redis/redis.conf
      regexp: 'protected-mode'
      line: 'protected-mode no'

  - name: Start and enabled mongodb service 
    ansible.builtin.service:
      name: redis
      state: started
      enabled: yes
